version: 0.2

phases:
  pre_build:
    commands:
      - echo "Setting up kubectl..."
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION
  build:
    commands:
      - echo "Deploying to EKS cluster..."
      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service.yaml
